export type BillingInterval = "monthly" | "annual";

// Presentation catalog. No checkout or subscription provisioning exists yet.
// Keep CTA destinations on the existing registration flow until billing is available.
export const subscriptionPlans = [
  {
    id: "plus",
    name: "Plus",
    description: "Great for individuals and small teams getting started.",
    monthlyPrice: { monthly: 29, annual: 23 },
    action: "Get started",
    href: "/register",
    accent: "text-emerald-700 bg-emerald-50",
    popular: false,
    features: [
      "50 interview sessions / month",
      "Up to 100 candidates",
      "AI-powered interview questions",
      "Basic reports & summaries",
      "AI follow-up questions",
      "Live interview with video and notes",
      "Email support",
    ],
    footer: "Perfect for recruiters, founders, and small hiring teams.",
  },
  {
    id: "pro",
    name: "Pro",
    description: "Everything you need for growing hiring teams.",
    monthlyPrice: { monthly: 79, annual: 63 },
    action: "Start free trial",
    href: "/register",
    accent: "text-blue-700 bg-blue-50",
    popular: true,
    features: [
      "250 interview sessions / month",
      "Up to 1,000 candidates",
      "Advanced reports & analytics",
      "AI follow-up questions & scoring",
      "Live interview with collaboration tools",
      "Interview templates & question banks",
      "Team collaboration up to 10 members",
      "Priority support",
    ],
    footer: "Ideal for scaling teams that want better data and smoother collaboration.",
  },
  {
    id: "business",
    name: "Business",
    description: "Built for large teams and organizations.",
    monthlyPrice: { monthly: 199, annual: 159 },
    action: "Contact sales",
    href: "/register",
    accent: "text-purple-700 bg-purple-50",
    popular: false,
    features: [
      "Unlimited interview sessions",
      "Unlimited candidates",
      "Enterprise-grade analytics & insights",
      "Custom AI question sets & workflows",
      "Live interviews with advanced controls",
      "Team collaboration with unlimited members",
      "SSO and organization-level access",
      "Dedicated success manager",
      "24/7 priority support",
    ],
    footer: "For organizations that hire at scale and need advanced control.",
  },
] as const;
